name: Fix prettier & eslint

# This action works with pull requests and pushes
on:
  pull_request:
  push:

jobs:
  fix-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Fix prettify
        uses: creyD/prettier_action@v3.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,md}

      - name: Fix eslint
        uses: stefanoeb/eslint-action@1.0.2
        with:
          files: src/
