name: Normalizar y testear código

# Se ejecuta cada vez que se hace push al repo
on: push

jobs:
  # Un job que nuclea a prettier & eslint y corre los tests.
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install modules npm
        run: npm install

      - name: Run prettier
        run: npm run prettify

      - name: Run eslint
        run: npm run lint -- --fix

      - name: Run tests
        run: npm run test

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Genera un commit de fixup para autosquashear fácilmente al
          # rebasear.
          commit_options: --fixup=HEAD
